export const ADD_QUIZ_REQUEST = "ADD_QUIZ_REQUEST";
export const ADD_QUIZ_SUCCESS = "ADD_QUIZ_SUCCESS";
export const ADD_QUIZ_FAILURE = "ADD_QUIZ_FAILURE";
export const CHANGE_INPUT_ANSWER = "CHANGE_INPUT_ANSWER";
export const COMPLETE_QUIZ = "COMPLETE_QUIZ";
export const CHANGE_INCORRECT_NOTE_PAGE = "CHANGE_INCORRECT_NOTE_PAGE";
export const CHANGE_IS_RESULT_VIEW = "CHANGE_IS_RESULT_VIEW";